from typing import List, Tuple, Dict, Any, Optional, Collection
import numpy as np

class PatientAI:
    def __init__(self) -> None: ...
    def answer_question(self, question: str) -> str: ...
    def diagnose_images(
        self,
        image_bytes_list: Optional[Collection[bytes]] = ...,
        processed_xrays: Optional[Collection[tuple[list[tuple[str, float]], list[dict[str, str | float | np.ndarray]]]]] = ...,
        symptoms: Optional[str] = ...,
        include_xray_image: bool = ...
    ) -> tuple[str, list[dict]] | str: ...