from typing import Union
import torch

def load_xray_image(image_input: Union[str, bytes]) -> torch.Tensor: ...
def process_xray_image(image_input: Union[str, bytes], threshold: float = ...) -> dict: ...