name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout the repo
        with:
          ref: ${{ github.ref }} # Đảm bảo checkout đúng branch/release hiện tại

      - name: Clear git cache and reset
        run: |
          git reset --hard HEAD
          git clean -fd
          git pull origin ${{ github.ref }} # Lấy mã nguồn mới nhất từ remote

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Clear pip cache
        run: |
          rm -rf ~/.cache/pip

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build release distributions
        run: |
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # Required for trusted publishing
      id-token: write

    environment:
      name: pypi
      # Update this to your PyPI project URL
      url: https://pypi.org/project/AFG_Gumball

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          # Using the provided PyPI token as a secret
          password: ${{ secrets.PYPI_API_TOKEN }}
